spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: product-service
  application:
    name: product-service
server:
  port: 0
  error:
    include-message: always
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:password@localhost:8761/eureka
